---
# tasks file for worker

- name: Setting Kubernetes repository
  yum_repository:
     name: kubernetes
     description: Kubernetes
     baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
     enabled: yes
     gpgcheck: yes
     repo_gpgcheck: yes
     gpgkey:
       - https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg  https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg



- name: Installing softwares
  yum: 
     name: "{{ item }}"
     state: present  
  loop: "{{ packages }}"

 

- name: Starting Services
  service: 
     name: "{{ item }}"
     state: started
     enabled: yes
  loop: "{{ services }}"   



- name: Docker daemon.json file
  copy:
      dest: /etc/docker/daemon.json
      content: "{{ doc_daemon }}"
   


- name: Restart docker services
  service:
    name: docker
    state: restarted
    enabled: yes 






- name: Creating conf directory
  file:
      path: /etc/systl.d/
      state: directory     



- name: Worker K8S conf file configuration
  copy: 
      dest: /etc/systl.d/k8s.conf
      content: "{{ k8s_conf }}"



- name: Creating fact directory
  file:
      path: /etc/ansible/facts.d/
      state: directory    

 

- name: Copy fact file from local to worker
  copy:
     dest: /etc/ansible/facts.d/master_token.fact
     src: "{{ copy_src_dir }}"
  ignore_errors: True



- name: nf call iptables.
  shell: echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables

 
#For updating the uploaded fact information.
- name: Re-gathering the updated facts.
  setup:
  register: updated_fcts
 

- name: Joining all worker nodes to Master node
  shell: "{{ ansible_local['master_token']['worker_token_cmd']['token_cmd'] }}"
  ignore_errors: True  
 


